// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prceggynifygenatnjun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY2VnZ3luaWZ5Z2VuYXRuanVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDQxNjQsImV4cCI6MjA2OTMyMDE2NH0.xsbjM4rNzbsyIwDgk82EjgLF0J-lb_tyUBscmjTTgnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});